biblionexus/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^read/(?P<book_id>[0-9]+)', include('read.urls')),
    url(r'^data/', include('data.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('browse.urls')),
]

browse/urls.py
from django.conf.urls import url

from . import views
app_name='browse'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

data/urls.py
from django.conf.urls import url

from . import views
app_name='data'
urlpatterns = [
    url(r'^$', views.add, name='add'),
    url(r'^(?P<book_id>[0-9]+)', views.edit, name='edit'),
    url(r'^author$', views.author, name='author'),
    url(r'^series$', views.series, name='series'),
]

read/urls.py
from django.conf.urls import url

from . import views
app_name='read'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

OPDS/models.py
from django.db import models

# Create your models here.

browse/models.py
from django.db import models

# Create your models here.

data/models.py
from django.forms import *
from django.db import models
import uuid
import os


class Author(models.Model):
    name = models.CharField(max_length=128, unique=True) #The name of the author

    def __str__(self):
        return self.name

class Series(models.Model):
    title = models.CharField(max_length=512, unique=True) #the title of the series
    authors = models.ManyToManyField(Author) #the authors that participated in the making of the series

    def __str__(self):
        return self.title + " by "+" and ".join(str(x) for x in self.authors.all())

def f(instance, filename):
        return 'data/static/data/books/'+str(uuid.uuid4())+".epub"

class Book(models.Model):
    title = models.CharField(max_length=512) #the title of the book
    authors = models.ManyToManyField(Author) #describes the author (or authors) of the book
    series = models.ForeignKey(Series, null=True, blank=True) #describes what series the book is in, if at all.  will be null if not there
    seriesSpot = models.IntegerField(default=0) #describes which book in the series this is, if 0, no series
    publish_date = models.DateField() #states the date that the book was published
    upload = models.FileField(upload_to=f)
    def filename(self):
        return os.path.basename(self.upload.name)

    def __str__(self):
        return self.title + " by "+" and ".join(str(x) for x in self.authors.all())

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['authors', 'title', 'series', 'seriesSpot', 'publish_date', 'upload', 'id']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control col-md-10'}),
            'publish_date': TextInput(attrs={'class': 'form-control com-md-10',  'required' : False}),
            'authors': SelectMultiple(attrs={'class': 'form-control col-md-10'}),
            'series': Select(attrs={'class': 'form-control col-md-10'}),
            'seriesSpot': TextInput(attrs={'class': 'form-control col-md-10'}),
            'id': TextInput(attrs={'required': False, 'readonly': True, 'type': 'hidden'}),
        }


class BookMark(models.Model):
    books = models.ManyToManyField(Book)
    page_place = models.IntegerField(default=0)

class Shelf(models.Model):
    title = models.CharField(max_length=512)
    books = models.ManyToManyField(Book)
    creation_date = models.DateField()

read/models.py
from django.db import models

# Create your models here.

OPDS/views.py
from django.shortcuts import render

# Create your views here.

browse/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from data.models import Book
# Create your views here.
def index(request):
    get_books = Book.objects.order_by("title")
    context = {
        'books_to_display': get_books,
    }
    return render(request, 'browse/index.html', context)

data/views.py
from django.forms import TextInput, SelectMultiple
from django.shortcuts import render, get_object_or_404, redirect
from .models import Series, Book, Author, BookForm, f
from django.http import HttpResponse
from django.template import loader
from django.forms import modelformset_factory
from django import forms
from django.core.files import File



# Create your views here.
def add(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            next = request.GET.get('from', None)
            if next:
                return redirect(next)
            else:
                return redirect("/")
        return HttpResponse("<H1>INVALID DATA, PLEASE TRY AGAIN.</H1><br/><FORM><INPUT Type='button' VALUE='Back' onClick='history.go(-1);return true;'></FORM>")
    else:
        form = BookForm()
    return render(request, 'data/add.html', {'formset': form, })

def author(request):
    authorFormSet = modelformset_factory(Author, fields=('name',), widgets={'name': TextInput(attrs={'class': 'form-control com-md-10',  'required' : True}),})
    if request.method == 'POST':
        formset = authorFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            next = request.GET.get('from', None)
            if next:
                return redirect(next)
            else:
                return redirect("/")
        return HttpResponse("<H1>INVALID DATA, PLEASE TRY AGAIN.</H1><br/><FORM><INPUT Type='button' VALUE='Back' onClick='history.go(-1);return true;'></FORM>")
    else:
        formset = authorFormSet(queryset=Author.objects.none())
    return render(request, 'data/author.html', {'formset': formset})

def series(request):
    seriesFormSet = modelformset_factory(Series, fields=('title', 'authors',), widgets={'title': TextInput(attrs={'class': 'form-control com-md-10',  'required': True}), 'authors': SelectMultiple(attrs={'class': 'form-control col-md-10'}), })
    if request.method == 'POST':
        formset = seriesFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            next = request.GET.get('from', None)
            if next:
                return redirect(next)
            else:
                return redirect("/")
        return HttpResponse("<H1>INVALID DATA, PLEASE TRY AGAIN.</H1><br/><FORM><INPUT Type='button' VALUE='Back' onClick='history.go(-1);return true;'></FORM>")
    else:
        formset = seriesFormSet(queryset=Series.objects.none())
    return render(request, 'data/series.html', {'formset': formset})


def edit(request, book_id):
    if request.method == 'POST':
        data=get_object_or_404(Book, id=book_id)
        form = BookForm(request.POST, request.FILES, instance=data)
        if form.is_valid():
            obj = form.save()
            next = request.GET.get('from', None)
            if next:
                return redirect(next)
            else:
                return redirect("/")
        return HttpResponse("<H1>INVALID DATA, PLEASE TRY AGAIN.</H1><br/><FORM><INPUT Type='button' VALUE='Back' onClick='history.go(-1);return true;'></FORM>")
    else:
        data=get_object_or_404(Book, id=book_id)
        form=BookForm(instance=data)

    return render(request, 'data/add.html', {'formset': form, })



#literally copied off of starting tutorial.  trying to get list of books by title show
#def sort_by_book(request):
#    book_list = Book.objects.filter(Book.title)
#    template = loader.get_template('templates/data/index.html')
#    context = {'book': Book.title}
#    return render(request, 'data/sort_by_book.html', context)

read/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
# Create your views here.
from data.models import Book

def index(request, book_id):
    book=get_object_or_404(Book, pk=book_id)
    return render(request, 'read/index.html', {'book': book})

browse/templates/browse/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta charset="UTF-8">
    <title>Browse Books</title>
    {% load staticfiles %}
    <script src="{% static "browse/js/jquery.min.js" %}"></script>
    <script src="{% static "read/js/js.cookie.js" %}"></script>
    <!-- begin bootstrap links -->
    <link rel="stylesheet" href="{% static "browse/bootstrap/css/bootstrap.min.css" %}">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">-->
    <script src="{% static "browse/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "browse/js/bootstrap-list-filter.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/bootstrap-material-design.css" %}">
    <script src="{% static "browse/material/js/material.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/ripples.css" %}">
    <script src="{% static "browse/material/js/ripples.min.js" %}"></script>
    <script>
        $.material.init();
    </script>
    <!-- end bootstrap links -->
    <style>
        .large {
            font-size: x-large;
        }

        .form-control-feedback {
            max-height: 28px;
            margin: 0;
            padding: 0;
        }
        span.glyphicon, a{
            top:50%
            vertical-align: middle;
        }
        .row-content:hover{
            background-color: #AAAAAA;
        }
    </style>
    <link rel="stylesheet" href="" id="css-theme"/>
    <script src="" id="js-theme"></script>
</head>
<body>
<div id="header" class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Biblionexus</a>
        </div>
        <div class="navbar-collapse collapse navbar-inverse-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="javascript:void(0)">List Books</a></li>
                <li><a href="{% url 'data:add' %}">Add Book
                    <div class="ripple-container"></div>
                </a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group is-empty">
                    <input id="search" type="text" class="form-control col-md-8" placeholder="Search">
                    <span class="material-input"></span>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="list-group" id="booklist">
    {% for book in books_to_display %}
        <div class="list-group-item">
        <div class="row-content" style="height: 100%;" onclick="window.location='{% url 'read:index' book.id %}'"><span class="large">{{ book.title }}
            by {{ book.authors.all | join:" and " }} {% if book.seriesSpot %}(Book {{ book.seriesSpot }} of {{ book.series }}) {% endif %}</span> <a class="large" href="{% url 'data:edit' book.id %}"><span
                class="glyphicon glyphicon-pencil"></span></a> <a class="large" href="{% static "data/books/"%}{{ book.filename }}"><span class="glyphicon glyphicon-download"></span></a></div></div>
    {% endfor %}
</div>
<script>
    $('#booklist').btsListFilter('#search', {initial: false});
</script>
</body>
</html>

data/templates/data/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta charset="UTF-8">
    <title>Create/Edit Book</title>
    {% load staticfiles %}
    <script src="{% static "browse/js/jquery.min.js" %}"></script>
    <script src="{% static "read/js/js.cookie.js" %}"></script>
    <!-- begin bootstrap links -->
    <link rel="stylesheet" href="{% static "browse/bootstrap/css/bootstrap.min.css" %}">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">-->
    <script src="{% static "browse/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "browse/js/bootstrap-list-filter.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/bootstrap-material-design.css" %}">
    <script src="{% static "browse/material/js/material.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/ripples.css" %}">
    <script src="{% static "browse/material/js/ripples.min.js" %}"></script>
    <script>
        $.material.init();
    </script>
    <link rel="stylesheet" href="" id="css-theme"/>
    <script src="" id="js-theme"></script>
    <style>
        p {
            font-size: 16px;
        }

        .form-group label {
            color: #333333;
        }
    </style>
</head>
<body>
<div id="header" class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Biblionexus</a>
        </div>
        <div class="navbar-collapse collapse navbar-inverse-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'browse:index' %}">List Books
                    <div class="ripple-container"></div>
                </a></li>
                <li class="active"><a href="javascript:void(0)">Add Book</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group is-empty">
                    <input id="search" type="text" class="form-control col-md-8" placeholder="Search">
                    <span class="material-input"></span>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="form">
    <form action="" method="post" class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}
            {{ formset.id }}
            <div class="form-group">
                <label for="id_title" class="col-md-1 control-label large"><p>Book Title</p></label>
                <div class="col-md-10">
                    {{ formset.title }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_authors" class="col-md-1 control-label large"><p>Authors</p> <span
                        onclick="window.location='{% url 'data:author' %}?from={{ request.path|urlencode }}'"
                        class="glyphicon glyphicon-plus"></span></label>
                <div class="col-md-10">
                    {{ formset.authors }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_series" class="col-md-1 control-label large"><p>Series</p>  <span
                        onclick="window.location='{% url 'data:series' %}?from={{ request.path|urlencode }}'"
                        class="glyphicon glyphicon-plus"></span></label>
                <div class="col-md-10">
                    {{ formset.series }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_seriesSpot" class="col-md-1 control-label large"><p># in series</p></label>
                <div class="col-md-10">
                    {{ formset.seriesSpot }}
                </div>
            </div>
            <div class="form-group">
                <label for="id_publish_date" class="col-md-1 control-label large"><p>Date Published</p></label>
                <div class="col-md-10">
                    {{ formset.publish_date }}
                </div>
            </div>
            <div>
                <label for="id_file" class="btn btn-default btn-file col-md-1 control-label large">{{ formset.upload }}</label>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" class="btn btn-raised btn-lg" value="Add Book"/>
            </div>

    </form>
</div>
</body>
</html>

data/templates/data/author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta charset="UTF-8">
    <title>Add Author</title>
    {% load staticfiles %}
    <script src="{% static "browse/js/jquery.min.js" %}"></script>
    <!-- begin bootstrap links -->
    <link rel="stylesheet" href="{% static "browse/bootstrap/css/bootstrap.min.css" %}">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">-->
    <script src="{% static "browse/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "browse/js/bootstrap-list-filter.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/bootstrap-material-design.css" %}">
    <script src="{% static "browse/material/js/material.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/ripples.css" %}">
    <script src="{% static "browse/material/js/ripples.min.js" %}"></script>
    <script>
        $.material.init();
    </script>
    <link rel="stylesheet" href="" id="css-theme"/>
    <script src="" id="js-theme"></script>
    <style>
        p {
            font-size: 16px;
        }

        .form-group label {
            color: #333333;
        }
    </style>
</head>
<body>
<div id="header" class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Biblionexus</a>
        </div>
        <div class="navbar-collapse collapse navbar-inverse-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'browse:index' %}">List Books
                    <div class="ripple-container"></div>
                </a></li>
                <li class="active"><a href="javascript:void(0)">Add Book</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group is-empty">
                    <input id="search" type="text" class="form-control col-md-8" placeholder="Search">
                    <span class="material-input"></span>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="form">
    <form action="" method="POST">
        {% csrf_token %}

        {{ formset.management_form }}
        <div class="form-group">
            <label for="id_form-0-name" class="col-md-1 control-label large"><p>Author Name</p></label>
            <div class="col-md-10">
                {{ formset.0.name }}
            </div>
        </div>
        <input type="submit" class="btn btn-raised btn-lg"  value="Add Author"/>
    </form>
</div>
</body>
</html>

data/templates/data/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

data/templates/data/series.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Series</title>
</head>
<body>
<div id="form">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta charset="UTF-8">
    <title></title>
    {% load staticfiles %}
    <script src="{% static "browse/js/jquery.min.js" %}"></script>
    <!-- begin bootstrap links -->
    <link rel="stylesheet" href="{% static "browse/bootstrap/css/bootstrap.min.css" %}">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">-->
    <script src="{% static "browse/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "browse/js/bootstrap-list-filter.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/bootstrap-material-design.css" %}">
    <script src="{% static "browse/material/js/material.min.js" %}"></script>
    <link rel="stylesheet" href="{% static "browse/material/css/ripples.css" %}">
    <script src="{% static "browse/material/js/ripples.min.js" %}"></script>
    <script>
        $.material.init();
    </script>
    <link rel="stylesheet" href="" id="css-theme"/>
    <script src="" id="js-theme"></script>
    <style>
        p {
            font-size: 16px;
        }

        .form-group label {
            color: #333333;
        }
    </style>
</head>
<body>
<div id="header" class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Biblionexus</a>
        </div>
        <div class="navbar-collapse collapse navbar-inverse-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'browse:index' %}">List Books
                    <div class="ripple-container"></div>
                </a></li>
                <li class="active"><a href="javascript:void(0)">Add Book</a></li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group is-empty">
                    <input id="search" type="text" class="form-control col-md-8" placeholder="Search">
                    <span class="material-input"></span>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="form">
    <form action="" method="POST">
        {% csrf_token %}

        {{ formset.management_form }}
        <div class="form-group">
            <label for="id_form-0-name" class="col-md-1 control-label large"><p>Series Title</p></label>
            <div class="col-md-10">
                {{ formset.0.title }}
            </div>
        </div>
        <br/>
        <div class="form-group">
            <label for="id_form-0-authors" class="col-md-1 control-label large"><p>Authors</p> <span onclick="window.location='{% url 'data:author' %}?from={{ request.path|urlencode }}'" class="glyphicon glyphicon-plus"></span></label>
            <div class="col-md-10">
                {{ formset.0.authors }}
            </div>
        </div>
        <br/>
        <input type="submit" class="btn btn-raised btn-lg" value="Add Series"/>
    </form>
</div>
</body>
</html>
</div>
</body>
</html>

read/templates/read/index.html
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    {% load staticfiles %}
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <script src="{% static "read/js/js.cookie.js" %}"></script>

    <link id="normalize-style" rel="stylesheet" href="{% static "read/css/normalize.css" %}">
    <link id="main-style" rel="stylesheet" href="{% static "read/css/main.css" %}">
    <link id="popup-style" rel="stylesheet" href="{% static "read/css/popup.css" %}">
    <script src="{% static "read/js/libs/jquery.min.js" %}"></script>
<script>

        if(Cookies.get("reader-theme")){
            var cssLink = document.createElement("link")
            cssLink.href = "style.css";
            cssLink.type = "text/css";
            cssLink.rel = "stylesheet";
            frames['frame1'].document.body.appendChild(cssLink);


            document.write(Cookies.get("reader-theme"))
        }

</script>




    <script src="{% static "read/js/libs/zip.min.js" %}"></script>

    <script>
        //"use strict";
        document.onreadystatechange = function () {
            if (document.readyState == "complete") {
                EPUBJS.filePath = "{% static "data/books/" %}";
                EPUBJS.cssPath = "{% static "read/css/" %}";
                // fileStorage.filePath = EPUBJS.filePath;
                window.reader = ePubReader("{% static "data/books/" %}{{ book.filename }}");
            }
        };
    </script>
    <script src="{% static "read/js/jquery.touchSwipe.min.js" %}"></script>
    <script>
        $(document).ready(function () {
            $("#main").swipe({
                //Generic swipe handler for all directions
                swipe: function (event, direction, distance, duration, fingerCount, fingerData) {
                    if (direction == "up" || direction == "right") {
                        window.reader.book.prevPage();
                    }else if(direction =="down" || direction == "left"){
                        window.reader.book.nextPage();
                    }
                }
            });

        });
    </script>
    <!-- File Storage -->
    <!-- <script src="js/libs/localforage.min.js"></script> -->

    <!-- Full Screen -->
    <script src="{% static "read/js/libs/screenfull.min.js" %}"></script>

    <!-- Render -->
    <script src="{% static "read/js/epub.min.js" %}"></script>

    <!-- Hooks -->
    <script src="{% static "read/js/hooks.min.js" %}"></script>

    <!-- Reader -->
    <script src="{% static "read/js/reader.min.js" %}"></script>

    <!-- Plugins -->
    <!-- <script src="js/plugins/search.js"></script> -->

    <!-- Highlights -->
    <!-- <script src="js/libs/jquery.highlight.js"></script> -->
    <!-- <script src="js/hooks/extensions/highlight.js"></script> -->

</head>
<body>
<div id="sidebar">
    <div id="panels">
        <input id="searchBox" placeholder="search" type="search">

        <a id="show-Search" class="show_view icon-search" data-view="Search">Search</a>
        <a id="show-Toc" class="show_view icon-list-1 active" data-view="Toc">TOC</a>
        <a id="show-Bookmarks" class="show_view icon-bookmark" data-view="Bookmarks">Bookmarks</a>
        <a id="show-Notes" class="show_view icon-edit" data-view="Notes">Notes</a>

    </div>
    <div id="tocView" class="view">
    </div>
    <div id="searchView" class="view">
        <ul id="searchResults"></ul>
    </div>
    <div id="bookmarksView" class="view">
        <ul id="bookmarks"></ul>
    </div>
    <div id="notesView" class="view">
        <div id="new-note">
            <textarea id="note-text"></textarea>
            <button id="note-anchor">Anchor</button>
        </div>
        <ol id="notes"></ol>
    </div>
</div>
<div id="main">

    <div id="titlebar">
        <div id="opener">
            <a id="slider" class="icon-menu">Menu</a>
        </div>
        <div id="metainfo">
            <span id="book-title"></span>
            <span id="title-seperator">&nbsp;&nbsp;–&nbsp;&nbsp;</span>
            <span id="chapter-title"></span>
        </div>
        <div id="title-controls">
            <a id="bookmark" class="icon-bookmark-empty">Bookmark</a>
            <a id="setting" class="icon-cog">Settings</a>
            <a id="fullscreen" class="icon-resize-full">Fullscreen</a>
        </div>
    </div>

    <div id="divider"></div>
    <div id="prev" class="arrow">‹</div>
    <div id="viewer"></div>
    <div id="next" class="arrow">›</div>

    <div id="loader"><img src="{% static "read/img/loader.gif" %}"></div>
</div>
<div class="modal md-effect-1" id="settings-modal">
    <div class="md-content">
        <h3>Settings</h3>

        <div>
            <p>
                <input type="checkbox" id="sidebarReflow" name="sidebarReflow">Reflow text when sidebars are open.
            </p>
        </div>
        <div class="closer icon-cancel-circled"></div>
    </div>
</div>
<div class="overlay"></div>
</body>
</html>